/**
 * Guest mode dummy data
 * Provides realistic sample data for all V2 screens so
 * unauthenticated users can explore the app.
 */

// ── Clients ──────────────────────────────────────────────

export const guestClients = [
    {
        id: 'gc1',
        name: 'Sarah Chen',
        company: 'Nexus Ventures',
        email: 'sarah@nexusventures.com',
        phone: '+1-555-0123',
        channels: [{ type: 'whatsapp', handle: '+1-555-0123' }, { type: 'email', handle: 'sarah@nexusventures.com' }],
        tags: ['series-a', 'branding', 'priority'],
        total_revenue: 14200,
        active_projects_count: 2,
        last_interaction_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        ai_notes: 'High-value client. Prefers quick WhatsApp updates. Decision-maker. Last engaged 30 mins ago — active conversation about brand identity.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    },
    {
        id: 'gc2',
        name: 'Marcus Rivera',
        company: 'TechCorp Inc.',
        email: 'marcus@techcorp.io',
        phone: '+1-555-0456',
        channels: [{ type: 'slack', handle: '#project-techcorp' }],
        tags: ['enterprise', 'web-dev', 'repeat'],
        total_revenue: 28500,
        active_projects_count: 1,
        last_interaction_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        ai_notes: 'Long-term client since 2024. Pays on time. Currently working on platform redesign. Prefers Slack for communication.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    },
    {
        id: 'gc3',
        name: 'Aisha Patel',
        company: 'GreenLeaf Organic',
        email: 'aisha@greenleaf.co',
        phone: null,
        channels: [{ type: 'email', handle: 'aisha@greenleaf.co' }],
        tags: ['e-commerce', 'shopify'],
        total_revenue: 4800,
        active_projects_count: 1,
        last_interaction_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
        ai_notes: 'New client. E-commerce project in discovery phase. Budget-conscious but enthusiastic.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    },
    {
        id: 'gc4',
        name: 'James Thornton',
        company: 'Thornton Legal',
        email: 'james@thorntonlegal.com',
        phone: '+1-555-0789',
        channels: [{ type: 'email', handle: 'james@thorntonlegal.com' }],
        tags: ['legal', 'website'],
        total_revenue: 6000,
        active_projects_count: 0,
        last_interaction_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
        ai_notes: 'Completed one project successfully. Last engaged 12 days ago — consider a check-in.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    },
    {
        id: 'gc5',
        name: 'Emily Zhang',
        company: null,
        email: 'emily.zhang@gmail.com',
        phone: '+1-555-0321',
        channels: [{ type: 'telegram', handle: '@emilyzhang' }],
        tags: ['freelance', 'mobile-app'],
        total_revenue: 0,
        active_projects_count: 0,
        last_interaction_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
        ai_notes: 'New inquiry about mobile app development. Seems serious — mentioned budget and timeline.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    },
];

// ── Leads ────────────────────────────────────────────────

export const guestLeads = [
    {
        id: 'gl1',
        title: 'Brand Identity Package',
        score: 0.92,
        priority: 'HOT',
        status: 'new',
        budget: 10000,
        client_name: 'Sarah Chen',
        client_id: 'gc1',
        ai_summary: 'Series A launch branding, $8-12K budget, deadline end of March. Decision-maker.',
        created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
    {
        id: 'gl2',
        title: 'Mobile App Development',
        score: 0.87,
        priority: 'HOT',
        status: 'contacted',
        budget: 15000,
        client_name: 'Emily Zhang',
        client_id: 'gc5',
        ai_summary: 'iOS/Android app for fitness tracking. $12-18K budget, 3-month timeline.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    },
    {
        id: 'gl3',
        title: 'E-commerce Store Setup',
        score: 0.72,
        priority: 'WARM',
        status: 'proposal_sent',
        budget: 5000,
        client_name: 'Aisha Patel',
        client_id: 'gc3',
        ai_summary: 'Shopify store for organic products. Proposal sent, awaiting feedback.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    },
    {
        id: 'gl4',
        title: 'Dashboard Redesign',
        score: 0.55,
        priority: 'COLD',
        status: 'new',
        budget: null,
        client_name: 'Marcus Rivera',
        client_id: 'gc2',
        ai_summary: 'Mentioned wanting analytics dashboard. No budget or timeline discussed yet.',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    },
];

// ── Projects ─────────────────────────────────────────────

export const guestProjects = [
    {
        id: 'gp1',
        title: 'Platform Redesign',
        client_id: 'gc2',
        client_name: 'Marcus Rivera',
        stage: 'active',
        status: 'on_track',
        budget: 18000,
        currency: 'USD',
        deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 21).toISOString().split('T')[0],
        start_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString().split('T')[0],
        description: 'Complete redesign of TechCorp platform UI/UX with new design system.',
        milestones: [
            { id: 'gm1', title: 'Wireframes & User Flows', due_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString().split('T')[0], completed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 16).toISOString(), sort_order: 0 },
            { id: 'gm2', title: 'High-Fidelity Designs', due_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString().split('T')[0], completed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(), sort_order: 1 },
            { id: 'gm3', title: 'Frontend Development', due_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString().split('T')[0], completed_at: null, sort_order: 2 },
            { id: 'gm4', title: 'QA & Launch', due_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 21).toISOString().split('T')[0], completed_at: null, sort_order: 3 },
        ],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    },
    {
        id: 'gp2',
        title: 'Brand Identity for Series A',
        client_id: 'gc1',
        client_name: 'Sarah Chen',
        stage: 'discovery',
        status: 'on_track',
        budget: 10000,
        currency: 'USD',
        deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 35).toISOString().split('T')[0],
        start_date: null,
        description: 'Complete brand identity package for Nexus Ventures Series A launch.',
        milestones: [],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    {
        id: 'gp3',
        title: 'Shopify Store Build',
        client_id: 'gc3',
        client_name: 'Aisha Patel',
        stage: 'proposal',
        status: 'on_track',
        budget: 5000,
        currency: 'USD',
        deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45).toISOString().split('T')[0],
        start_date: null,
        description: 'Custom Shopify store for GreenLeaf Organic products.',
        milestones: [],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    },
    {
        id: 'gp4',
        title: 'Law Firm Website',
        client_id: 'gc4',
        client_name: 'James Thornton',
        stage: 'completed',
        status: 'on_track',
        budget: 6000,
        currency: 'USD',
        deadline: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString().split('T')[0],
        start_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString().split('T')[0],
        description: 'Professional website for Thornton Legal with CMS.',
        milestones: [
            { id: 'gm5', title: 'Design Mockups', due_date: null, completed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(), sort_order: 0 },
            { id: 'gm6', title: 'Development', due_date: null, completed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(), sort_order: 1 },
            { id: 'gm7', title: 'Launch', due_date: null, completed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(), sort_order: 2 },
        ],
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    },
];

// ── Invoices ─────────────────────────────────────────────

export const guestInvoices = [
    {
        id: 'ginv1',
        client_id: 'gc2',
        client_name: 'Marcus Rivera',
        project_id: 'gp1',
        project_name: 'Platform Redesign',
        amount: 9000,
        status: 'paid',
        due_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString().split('T')[0],
        description: 'Platform Redesign - Milestone 1 & 2',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    },
    {
        id: 'ginv2',
        client_id: 'gc4',
        client_name: 'James Thornton',
        project_id: 'gp4',
        project_name: 'Law Firm Website',
        amount: 6000,
        status: 'paid',
        due_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString().split('T')[0],
        description: 'Law Firm Website - Full project',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    },
    {
        id: 'ginv3',
        client_id: 'gc2',
        client_name: 'Marcus Rivera',
        project_id: 'gp1',
        project_name: 'Platform Redesign',
        amount: 4500,
        status: 'sent',
        due_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString().split('T')[0],
        description: 'Platform Redesign - Milestone 3',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    },
    {
        id: 'ginv4',
        client_id: 'gc1',
        client_name: 'Sarah Chen',
        project_id: 'gp2',
        project_name: 'Brand Identity for Series A',
        amount: 3000,
        status: 'draft',
        due_date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString().split('T')[0],
        description: 'Brand Identity - Discovery phase deposit',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    },
    {
        id: 'ginv5',
        client_id: 'gc3',
        client_name: 'Aisha Patel',
        project_id: null,
        project_name: null,
        amount: 1500,
        status: 'overdue',
        due_date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString().split('T')[0],
        description: 'Consultation & Initial Research',
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 17).toISOString(),
    },
];

// ── Today Screen Data ────────────────────────────────────

export const guestTodayData = {
    priority: [
        { id: 'gpa1', title: 'Reply to Sarah Chen', description: 'Hot lead — brand identity project, $10K budget', type: 'reply', urgency: 'high' },
        { id: 'gpa2', title: 'Invoice overdue: Aisha Patel', description: '$1,500 overdue by 3 days', type: 'invoice', urgency: 'high' },
        { id: 'gpa3', title: 'Milestone due: Frontend Development', description: 'Platform Redesign — due in 10 days', type: 'milestone', urgency: 'medium' },
        { id: 'gpa4', title: 'Follow up with Emily Zhang', description: 'Mobile app inquiry — 3 hours ago', type: 'follow_up', urgency: 'medium' },
        { id: 'gpa5', title: 'Send proposal to Aisha Patel', description: 'Shopify store — proposal pending', type: 'proposal', urgency: 'low' },
    ],
    opportunities: [
        { id: 'gl1', clientName: 'Sarah Chen', title: 'Brand Identity Package', score: 0.92, budget: 10000, summary: 'Series A branding, $8-12K budget, March deadline' },
        { id: 'gl2', clientName: 'Emily Zhang', title: 'Mobile App Development', score: 0.87, budget: 15000, summary: 'Fitness app, $12-18K, 3-month timeline' },
        { id: 'gl3', clientName: 'Aisha Patel', title: 'E-commerce Store', score: 0.72, budget: 5000, summary: 'Shopify store, proposal sent' },
    ],
    money: {
        paidThisMonth: 15000,
        outstanding: 6000,
        expected: 3000,
        overdueCount: 1,
        netIncome: 15000,
    },
    momentum: {
        replyPendingCount: 3,
        idleConversations: 2,
    },
};

// ── Inbox / Conversations ────────────────────────────────

export const guestConversations = [
    {
        id: 'gconv1',
        client_name: 'Sarah Chen',
        client_id: 'gc1',
        channel: 'whatsapp',
        last_message: 'Hi! We need a complete brand identity for our Series A launch. Budget is $8,000-12,000 and we need it done by end of March.',
        last_message_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        unread_count: 2,
        lead_score: 0.92,
        ai_summary: 'Hot lead — brand identity for Series A. Budget $8-12K, deadline March.',
        status: 'active',
    },
    {
        id: 'gconv2',
        client_name: 'Marcus Rivera',
        client_id: 'gc2',
        channel: 'slack',
        last_message: 'The high-fidelity designs look great! Can we schedule a review call?',
        last_message_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        unread_count: 1,
        lead_score: null,
        ai_summary: 'Client approved designs, requesting review call for next milestone.',
        status: 'active',
    },
    {
        id: 'gconv3',
        client_name: 'Emily Zhang',
        client_id: 'gc5',
        channel: 'telegram',
        last_message: 'I am looking for someone to build a fitness tracking app. We have a budget of $12-18K.',
        last_message_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
        unread_count: 1,
        lead_score: 0.87,
        ai_summary: 'New hot lead — mobile app, $12-18K budget, 3-month timeline.',
        status: 'active',
    },
    {
        id: 'gconv4',
        client_name: 'Aisha Patel',
        client_id: 'gc3',
        channel: 'email',
        last_message: 'Thanks for the proposal! I need to discuss it with my partner. Will get back to you by Friday.',
        last_message_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
        unread_count: 0,
        lead_score: 0.72,
        ai_summary: 'Proposal under review — expect response by Friday.',
        status: 'active',
    },
    {
        id: 'gconv5',
        client_name: 'James Thornton',
        client_id: 'gc4',
        channel: 'email',
        last_message: 'The website is performing really well! Thank you for the great work.',
        last_message_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
        unread_count: 0,
        lead_score: null,
        ai_summary: 'Project completed. Happy client — potential for referrals.',
        status: 'idle',
    },
];

// ── Money Summary ────────────────────────────────────────

export const guestMoneySummary = {
    earnedThisMonth: 15000,
    outstanding: 6000,
    expected: 3000,
    overdueCount: 1,
    netIncome: 15000,
};
